# Generated by Django 6.1 on 2026-08-20 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('descripcion_corta', models.CharField(max_length=280)),
                ('edad_recomendada', models.PositiveSmallIntegerField(help_text='Edad mínima recomendada, en años (0-18).')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy alto')], max_length=10)),
                ('justificacion', models.TextField(help_text='Explicación breve de por qué se asignó esta edad/riesgo.')),
                ('fuente', models.CharField(choices=[('curada', 'Base de datos curada'), ('ia', 'Estimación por IA')], default='curada', max_length=10)),
                ('fuente_detalle', models.CharField(blank=True, help_text='Ej: Common Sense Media, App Store, PEGI, ESRB.', max_length=200)),
                ('logo_emoji', models.CharField(blank=True, help_text='Emoji simple para mostrar mientras no haya logo real.', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FactorRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(max_length=280)),
                ('categoria', models.CharField(choices=[('contacto', 'Contacto con desconocidos'), ('contenido', 'Contenido inapropiado'), ('privacidad', 'Privacidad y datos'), ('economico', 'Riesgo económico'), ('psicosocial', 'Impacto psicosocial')], max_length=20)),
                ('icono', models.CharField(default='alert-triangle', help_text='Nombre de icono (lucide) para mostrar en la UI.', max_length=40)),
            ],
            options={
                'verbose_name': 'Factor de riesgo',
                'verbose_name_plural': 'Factores de riesgo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=150)),
                ('resuelta_por_ia', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('app_encontrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas', to='detector.app')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='app',
            name='factores',
            field=models.ManyToManyField(blank=True, related_name='apps', to='detector.factorriesgo'),
        ),
    ]
